name: splitstack_grpc_generated
description: Generated gRPC code from splitstack-grpc-api
version: 1.1.3
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  protobuf: ^6.0.0
  grpc: ^5.1.0
  fixnum: ^1.1.1
